show-sethome-message: true
sethome-message: '&8[&7Server&8]&7Your home position updated!'
show-teleport-message: false
teleport-message: '&8[&7Server&8]&7Teleporting to home...'
play-warp-sound: true
respawn-player-at-home: true
home-command-delay: true
home-time-delay: 3

playerName:
  format: "%-16s"
deathCount:
  format: " %d"
  position: end

times:
  night: 0
  morning: 0
  day: 0
  evening: 0

ticks: 10
default-on: false
Players: []