#BecvoldCore config

ticks: 10 #Coordinates Hud config
default-on: false
Players: []


times: # Time util config
  night: 0 # 0 is normal time
  morning: 0 # 0 is normal time
  day: 15  # 15 = day is 15x longer then normal
  evening: 0 # 0 is normal time


#Others