#BecvoldCore config

#Coordinates Hud config
ticks: 10
default-on: false
Players: []


# Time util config
times:
  night: 0 # 0 is normal time
  morning: 0 # 0 is normal time
  day: 15  # 15 = day is 15x longer then normal
  evening: 0 # 0 is normal time


#Others